# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cage < Formula
  desc "Cross-platform sandbox CLI for restricting filesystem access"
  homepage "https://github.com/RutgerLubbers/cage"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RutgerLubbers/cage/releases/download/v0.2.0/cage_Darwin_x86_64.tar.gz"
      sha256 "66e78ae3753e982e9979c19bcbf10589d508e93fd2eede3fab14321a200dda4a"

      def install
        bin.install "cage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RutgerLubbers/cage/releases/download/v0.2.0/cage_Darwin_arm64.tar.gz"
      sha256 "ec3abdb3909db5a6205e8206665b7c855785e65b2c7d15d317f5af0acbfaafce"

      def install
        bin.install "cage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RutgerLubbers/cage/releases/download/v0.2.0/cage_Linux_x86_64.tar.gz"
      sha256 "0dd00a0ec5505165da6f7c9bcf556b2079830acb20f9f09c2d13988345609680"
      def install
        bin.install "cage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RutgerLubbers/cage/releases/download/v0.2.0/cage_Linux_arm64.tar.gz"
      sha256 "0e83c2dfa30f0411b434c58152c19a33346f7f7818c0ffd8d6457fba7599cca5"
      def install
        bin.install "cage"
      end
    end
  end

  test do
    system "#{bin}/cage", "--version"
  end
end
